import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'CUSTOMIZATION',
    {
        type: 'autogenerated',
        dirName: 'governance',
    },
    {
        type: 'autogenerated',
        dirName: 'reports',
    }
  ],
};

export default sidebars;